In [1]:


!pip install numpy

# Numpy

Importing Numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
a=np.array([[1,2,3],[4,5,6]])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(2, 3)

Creating another variable as b

In [9]:
b=np.arange(10)

In [10]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
b1=b+2

In [12]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(b1)

[ 2  3  4  5  6  7  8  9 10 11]


In [14]:
a=np.array([ 2,3,4,5,6,7,8,9,10,11])

In [15]:
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


In [16]:
a[0]

2

In [17]:
a[9]

11

In [20]:
a[[0,2,3]]

array([2, 4, 5])

In [21]:
a[0:7:1]

array([2, 3, 4, 5, 6, 7, 8])

# creating n-dimensional array

In [23]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [24]:
a.shape

(4, 4)

In [25]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
a[0:3,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [27]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

# Creating Random

In [29]:
print(np.random.random())

0.6828035186370423


# Seed value

If we want stable output for Random, then you have to create Seed value

In [47]:
np.random.seed(10)
print(np.random.random())

0.771320643266746


Random Int

In [48]:
a=np.random.randint(low=1,high=10,size=5)

In [50]:
print(a)

[5 1 2 1 2]


In [51]:
a=np.random.randint(low=3,high=5,size=7)
print(a)

[3 3 4 3 3 3 3]


new code

In [52]:
a=np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [53]:
x=a.reshape(6,5)

In [54]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [58]:
y=a.reshape(30)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
y=a.reshape(30,1)

In [60]:
y


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])