# Numpy practice


In [9]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5])    # created array

In [11]:
arr.shape                    # check the shape

(5,)

In [12]:
print(arr)                   # print array 

[1 2 3 4 5]


In [13]:
a=np.arange(10)             # Create a NumPy array 'a' containing integers from 0 to 9 in sequence.

In [14]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a=a+2                       # Add 2 to each element in the array 'a' and update the array with the new values.

In [16]:
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


In [17]:
print(a+2)                  # Print the result of adding 2 to each element in the array 'a', without modifying 'a' itself.

[ 4  5  6  7  8  9 10 11 12 13]


In [18]:
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


## Slicing

In [19]:
a[0:8:1]                # Extract a subarray from 'a' starting at index 0, ending at index 7 (8-1), with a step size of 1.

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a[0]

2

# Creating n-dimensional array

In [21]:
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a.shape

(4, 4)

#### Slicing of n-dimensional array

In [36]:
a[0:3,0:2]              # Extract a subarray from 'a' including rows from index 0 to 2 and columns from index 1 to 2

array([[0, 4],
       [1, 5],
       [2, 6]])

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Created new array

In [26]:
a=np.array([[0,1,2],[4,5,6],[8,9,10],[12,13,14]])

In [27]:
a

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [28]:
a=a.T                  # Transpose the array 'a', swapping rows and columns.

In [29]:
a

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [30]:
a.reshape(4,3)          # reshape the array

array([[ 0,  4,  8],
       [12,  1,  5],
       [ 9, 13,  2],
       [ 6, 10, 14]])

## Creating  Random

In [31]:
np.random.random()

0.13127875248997356

In [32]:
np.random.random(10) # it will create 10 random value

array([0.57033925, 0.76577964, 0.30884223, 0.72136859, 0.13971403,
       0.91652115, 0.33539641, 0.18434807, 0.05502272, 0.08541679])

#### Seed:-

**The seed value in NumPy's random module is used to initialize the random number generator, ensuring that the same sequence of random numbers can be reproduced when the same seed is used.**

In [33]:
np.random.seed(10)                              
print(np.random.random()) # Set the random seed to ensure reproducibility,& generate and print a random number between 0 and 1.

0.771320643266746


##### Creating randint

In [34]:
np.random.randint(low=5,high=7,size=6)        # Generate an array of 6 random integers between 5 and 7.

array([5, 6, 5, 6, 6, 5])